export const GET_MESSAGES = "GET_MESSAGES";
export const ADD_MESSAGES = "ADD_MESSAGES";
export const USER_MESSAGE = "USER_MESSAGE";
export const BOT_TEXT_MESSAGE = "BOT_TEXT_MESSAGE";
export const BOT_QUICKREPLIES = "BOT_QUICKREPLIES";
export const BOT_CARDS = "BOT_CARDS";
export const BOT_IMAGE = "BOT_IMAGE";
export const BOT_VIDEO = "BOT_VIDEO";

export const BOT_SENDING = "BOT_SENDING";
export const HOME_BUTTON = "HOME_BUTTON";
export const HIDE_QUICK_REPLIES = "HIDE_QUICK_REPLIES";
export const BOT_TYPING_BUBBLE = "BOT_TYPING_BUBBLE";
export const USER_MESSAGE_SENT = "USER_MESSAGE_SENT";
